services:
  web:
    build: .
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 8000:8000

  db:
    image: postgres:18
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}

volumes:
  postgres_data:
